#!/usr/bin/env python3
"""Generate all 10 Supermemory tutorial Jupyter notebooks."""
import json, os

BASE = "/c/Users/guhar/ws/calude_tutorial/supermemory/notebooks"
os.makedirs(BASE, exist_ok=True)

M, C = "markdown", "code"

def save(name, cells):
    nb = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0"}
        },
        "cells": [{"cell_type": ct, "metadata": {}, "source": sl, "outputs": []} for ct, sl in cells]
    }
    with open(os.path.join(BASE, name), "w") as f:
        json.dump(nb, f, indent=1)
    print(f"  OK  {name}")

# ============================================================
# NOTEBOOK 01: Introduction & Setup
# ============================================================

save("01_introduction_and_setup.ipynb", [

(M, ["# 01 -- Introduction and Setup\n", "\n",
     "## What We'll Cover\n",
     "1. What Supermemory is (the mental model)\n",
     "2. Getting an API key\n",
     "3. Installing the Python SDK\n",
     "4. Creating your first client\n",
     "5. Understanding the architecture\n",
     "6. Verifying connectivity\n"]),

(M, ["## 1.1 What Is Supermemory?\n", "\n",
     "Supermemory is a **memory and context engine** for AI agents. "
     "It solves the \"Goldfish Memory\" problem -- AI systems forgetting everything "
     "between conversations. Think of it as a **living knowledge graph** -- "
     "not a static document store.\n", "\n",
     "It's ranked #1 on all three major AI memory benchmarks: "
     "**LongMemEval** (81.6%), **LoCoMo**, and **ConvoMem**.\n", "\n",
     "### Core Capabilities\n",
     "| Capability | What It Does |\n",
     "|------------|-------------|\n",
     "| Memory Extraction | Reads conversations and documents, extracts meaningful facts |\n",
     "| User Profiles | Auto-builds static (long-term) and dynamic (recent) user context |\n",
     "| Hybrid Search | Vector + keyword search with sub-300ms latency |\n",
     "| Graph Relationships | Connects memories via Updates, Extends, and Derives |\n",
     "| Auto-Forgetting | Expired or temporary facts decay automatically |\n",
     "| Connectors | Google Drive, Notion, Gmail, OneDrive, GitHub sync |\n"]),

(M, ["## 1.2 Getting an API Key\n", "\n",
     "1. Go to **console.supermemory.ai** and sign up\n",
     "2. Navigate to **API Keys** -> **Create API Key**\n",
     "3. Name it (e.g., \"tutorial\") and optionally set an expiry\n",
     "4. Copy the key -- it starts with `sm_`\n", "\n",
     "**Free Tier:** 100K tokens stored at no cost with full API access.\n", "\n",
     "**Alternative: Self-Host** -- single binary, free, no limits:\n",
     "```bash\n",
     "curl -fsSL https://supermemory.ai/install | bash\n",
     "```\n"]),

(C, ["# 1.3 Install and verify the Python SDK\n",
     "# Run in terminal: pip install supermemory\n",
     "import supermemory\n",
     "print(f\"Supermemory SDK version: {supermemory.__version__}\")\n"]),

(C, ["# 1.4 Create your first client\n",
     "from supermemory import Supermemory\n", "\n",
     "# The SDK auto-reads SUPERMEMORY_API_KEY from environment\n",
     "# Set it: export SUPERMEMORY_API_KEY=\"sm_...\"\n",
     "client = Supermemory()\n", "\n",
     "# Or pass explicitly:\n",
     "# client = Supermemory(api_key=\"sm_...\")\n", "\n",
     "# For self-hosted:\n",
     "# client = Supermemory(api_key=\"...\", base_url=\"http://localhost:6767\")\n", "\n",
     "print(f\"Client ready. Base URL: {client.base_url}\")\n"]),

(C, ["# 1.5 Add your first memory -- verify everything works\n",
     "response = client.add(\n",
     "    content=(\n",
     '        "Hello, Supermemory! My name is Alex. '\n",
     '        "I am a software engineer specializing in distributed systems. "\n',
     '        "I love Python and Rust."\n',
     "    ),\n",
     '    container_tag="tutorial_user_alex"\n',
     ")\n", "\n",
     "print(f\"Document ID: {response.id}\")\n",
     "print(f\"Status: {response.status}\")  # 'queued' or 'done'\n",
     "print(\"Memory added! Supermemory will now extract facts from this.\")\n"]),

(C, ["# 1.6 Retrieve context -- get user profile\n",
     "# profile() returns static facts + dynamic context + search results\n",
     "# All in ONE call (~50ms)\n",
     "profile = client.profile(\n",
     '    container_tag="tutorial_user_alex",\n',
     '    q="What does Alex do?"  # optional: find relevant past memories\n',
     ")\n", "\n",
     "print(\"=== Static Profile (long-term facts) ===\")\n",
     "for fact in profile.profile.static:\n",
     "    print(f\"  * {fact}\")\n", "\n",
     "print()\n",
     "print(\"=== Dynamic Profile (recent context) ===\")\n",
     "for fact in profile.profile.dynamic:\n",
     "    print(f\"  * {fact}\")\n", "\n",
     "print()\n",
     "print(\"=== Relevant Search Results ===\")\n",
     "for result in profile.search_results.results[:5]:\n",
     "    memory_text = result.get(\"memory\", str(result))\n",
     "    score = result.get(\"score\", \"N/A\")\n",
     "    print(f\"  [{score}] {memory_text[:100]}...\")\n"]),

(C, ["# 1.7 Configuration Options\n",
     "print(\"Key configuration options:\")\n",
     "print(\"  timeout: Supermemory(timeout=120.0)  -- default 60s\")\n",
     "print(\"  max_retries: Supermemory(max_retries=5)  -- default 2\")\n",
     "print(\"  base_url: For self-hosted servers\")\n",
     "print(\"  SUPERMEMORY_LOG=info|debug  -- enable SDK logging\")\n",
     "print()\n",
     "print(\"Integration ecosystem:\")\n",
     "print(\"  AI Coding: Claude Code, Codex CLI, OpenCode, Hermes\")\n",
     "print(\"  Frameworks: Vercel AI SDK, LangChain, Mastra\")\n",
     "print(\"  MCP: Claude Desktop, Cursor, Windsurf, VS Code\")\n"]),

(M, ["## 1.8 Key Takeaways\n", "\n",
     "- Supermemory is a **living knowledge graph**, not static storage\n",
     "- The SDK auto-reads `SUPERMEMORY_API_KEY` from your environment\n",
     "- `add()` ingests content -- Supermemory extracts memories automatically\n",
     "- `profile()` returns user context (static + dynamic) in one ~50ms call\n",
     "- Self-hosting is a single binary, zero config, fully offline capable\n", "\n",
     "**Next:** Notebook 02 -- Adding Memories (text, URLs, files, bulk operations)\n"]),
])

# ============================================================
# NOTEBOOK 02: Adding Memories
# ============================================================

save("02_adding_memories.ipynb", [

(M, ["# 02 -- Adding Memories\n", "\n",
     "## What We'll Cover\n",
     "1. Adding text content\n",
     "2. Adding URLs (auto-extracted)\n",
     "3. Uploading files (PDFs, images, videos)\n",
     "4. Using `customId` for updates and deduplication\n",
     "5. Scoping with `containerTag` and `containerTags`\n",
     "6. Bulk ingestion strategies\n"]),

(M, ["## 2.1 The `add()` Method\n", "\n",
     "The core ingestion method. Send any raw content and Supermemory extracts memories automatically.\n", "\n",
     "**Parameters:**\n",
     "- `content` (str): Text, URL, or raw content to process\n",
     "- `container_tag` (str): Single tag for scoping (user ID, project ID)\n",
     "- `container_tags` (list[str]): Multiple tags for cross-cutting scopes\n",
     "- `metadata` (dict): Key-value pairs for filtering and organization\n",
     "- `custom_id` (str): YOUR identifier to enable updates and prevent duplicates\n",
     "- `user_id` (str): Partition data to a specific user space\n"]),

(C, ["# 2.2 Adding basic text content\n",
     "from supermemory import Supermemory\n",
     "client = Supermemory()\n", "\n",
     "# Simplest form -- just content and a container tag\n",
     "response = client.add(\n",
     '    content="Machine learning enables computers to learn from data "\n',
     '             "without explicit programming.",\n',
     '    container_tag="user_001"\n',
     ")\n",
     "print(f\"ID: {response.id}, Status: {response.status}\")\n"]),

(C, ["# 2.3 Adding conversation transcripts (the PRIMARY use case)\n",
     "conversation = [\n",
     '    {"role": "assistant", "content": "Hello! How can I help you today?"},\n',
     '    {"role": "user", "content": "Hi! I am Sarah. I am a product designer "\n',
     '                               "at Figma. I love design systems and coffee."},\n',
     '    {"role": "user", "content": "Can you help me design a dashboard layout?"},\n',
     "]\n", "\n",
     "# Join the conversation into a single text block\n",
     'conv_text = "\n".join(f\"{m[\"role\"]}: {m[\"content\"]}\" for m in conversation)\n',
     "print(\"Sending conversation:\")\n",
     "print(conv_text)\n", "\n",
     "response = client.add(\n",
     "    content=conv_text,\n",
     '    container_tag="user_sarah",\n',
     '    metadata={"type": "conversation", "topic": "design"}\n',
     ")\n",
     "print(f\"\nStored! ID: {response.id}, Status: {response.status}\")\n"]),

(C, ["# 2.4 Adding URLs -- Supermemory auto-extracts page content\n",
     "response = client.add(\n",
     '    content="https://supermemory.ai/docs/introduction",\n',
     '    container_tag="knowledge_base",\n',
     '    metadata={"source": "web", "category": "documentation"}\n',
     ")\n",
     "print(f\"URL queued for extraction: {response.id}\")\n",
     "print(\"Note: URL extraction happens asynchronously.\")\n",
     "print(\"Content will be searchable once processing completes.\")\n"]),

(C, ["# 2.5 Multi-scope with containerTags\n",
     "# containerTags lets you scope a memory to multiple dimensions\n",
     "response = client.memory.create(\n",
     '    content="The auth service needs OAuth2 and SAML for enterprise customers.",\n',
     '    containerTags=["user_001", "project_auth", "team_engineering"],\n',
     '    metadata={"priority": "high", "status": "planned"}\n',
     ")\n",
     "print(f\"Multi-tagged memory: {response.id}\")\n",
     "print(\"Scoped to: user_001, project_auth, team_engineering\")\n"]),

(C, ["# 2.6 Using customId -- prevent duplicates, enable updates\n",
     "# customId is YOUR identifier. Same customId = update, not duplicate.\n", "\n",
     "# First addition\n",
     "r1 = client.add(\n",
     '    content="user: Hi, I am Sarah.\nassistant: Nice to meet you, Sarah!",\n',
     '    custom_id="conv_001",\n',
     '    container_tag="user_sarah"\n',
     ")\n",
     "print(f\"First add: {r1.id}\")\n", "\n",
     "# Later: more messages in same conversation (same customId)\n",
     "r2 = client.add(\n",
     '    content="user: What is the weather today?\n"\n',
     '             "assistant: It is sunny and 72 degrees!",\n',
     '    custom_id="conv_001",  # Same ID -- Supermemory links them\n',
     '    container_tag="user_sarah"\n',
     ")\n",
     "print(f\"Update: {r2.id} (linked to conv_001)\")\n"]),

(C, ["# 2.7 Uploading files (PDFs, images, videos)\n",
     "from pathlib import Path\n", "\n",
     "# Upload a PDF (extracts text + builds memories)\n",
     "# client.documents.upload_file(\n",
     "#     file=Path(\"/path/to/report.pdf\"),\n",
     "#     container_tags=[\"user_001\"],\n",
     "#     metadata={\"type\": \"report\"}\n",
     "# )\n", "\n",
     "print(\"Supported file formats:\")\n",
     "print(\"  PDF: Full text extraction + chunking + embedding\")\n",
     "print(\"  Images: OCR for text in images\")\n",
     "print(\"  Videos: Transcription\")\n",
     "print(\"  Code: AST-aware semantic chunking\")\n",
     "print()\n",
     "print(\"Processing times:\")\n",
     "print(\"  PDF (100 pages): ~1-2 minutes\")\n",
     "print(\"  Video (1 hour): ~5-10 minutes\")\n"]),

(C, ["# 2.8 Bulk ingestion -- add multiple items\n",
     "contents = [\n",
     '    ("Alice is a backend engineer specializing in Go and Kubernetes.", "user_alice"),\n',
     '    ("Bob is a frontend engineer who loves React and design systems.", "user_bob"),\n',
     '    ("Carol is a data scientist working with PyTorch and JAX.", "user_carol"),\n',
     '    ("The team uses AWS and GitHub Actions for CI/CD.", "team_eng"),\n',
     '    ("Sprint 42 focuses on migrating the monolith to microservices.", "sprint_42"),\n',
     "]\n", "\n",
     "results = []\n",
     "for content, tag in contents:\n",
     "    r = client.add(content=content, container_tag=tag)\n",
     "    results.append(r)\n",
     "    print(f\"Added [{tag}]: {r.id}\")\n", "\n",
     "print(f\"\nTotal ingested: {len(results)} documents\")\n",
     "print(\"Tip: For large batches, use AsyncSupermemory (see Notebook 07)\")\n"]),

(M, ["## 2.9 Content Types Reference\n", "\n",
     "| Type | Example | Processing |\n",
     "|------|---------|------------|\n",
     "| Text | Free-form text, markdown notes | Direct extraction |\n",
     "| Conversations | Chat transcripts | Role-aware chunking |\n",
     "| URLs | Web pages, YouTube links | Full-content extraction + indexing |\n",
     "| PDFs | Documents, reports | Text extraction + semantic chunking |\n",
     "| Images | Screenshots, photos with text | OCR for embedded text |\n",
     "| Videos | Recordings, tutorials | Speech-to-text transcription |\n",
     "| Code | Source files | AST-aware semantic chunking |\n", "\n",
     "## 2.10 Key Takeaways\n", "\n",
     "- Use `container_tag` for single-scope, `containerTags` for multi-scope\n",
     "- Use `custom_id` to link updates and prevent duplicate memories\n",
     "- URLs are auto-extracted -- just pass the URL as the content\n",
     "- File uploads support PDFs, images (OCR), video (transcription)\n",
     "- Processing is asynchronous -- status starts as `queued`\n", "\n",
     "**Next:** Notebook 03 -- Searching Memories\n"]),
])

# ============================================================
# NOTEBOOK 03: Searching Memories
# ============================================================

save("03_searching_memories.ipynb", [

(M, ["# 03 -- Searching Memories\n", "\n",
     "## What We'll Cover\n",
     "1. Basic semantic search\n",
     "2. Hybrid search (vector + keyword)\n",
     "3. Threshold tuning for precision vs recall\n",
     "4. Pagination and result limits\n",
     "5. Scoped search with container tags\n",
     "6. Search modes and optimization\n"]),

(M, ["## 3.1 Two Search APIs\n", "\n",
     "Supermemory offers two search interfaces:\n",
     "- **`client.search.execute(q, ...)`** -- General search across everything\n",
     "- **`client.search.documents(q, container_tags, ...)`** -- Scoped search within containers\n", "\n",
     "Both support hybrid search (vector + keyword) with sub-300ms latency.\n", "\n",
     "**The recommended pattern:** Use `profile(container_tag, q=query)` instead of separate "
     "search calls when you need both user context and search results. "
     "One call gets you static facts + dynamic facts + relevant memories.\n"]),

(C, ["# 3.2 Basic semantic search\n",
     "from supermemory import Supermemory\n",
     "client = Supermemory()\n", "\n",
     "# Search across all accessible documents\n",
     "results = client.search.execute(\n",
     '    q="machine learning and AI concepts"\n',
     ")\n", "\n",
     "print(f\"Found {len(results.results)} results:\")\n",
     "for i, r in enumerate(results.results[:5], 1):\n",
     "    memory_text = r.get(\"memory\", str(r))\n",
     "    score = r.get(\"score\", \"N/A\")\n",
     "    print(f\"  {i}. [{score}] {memory_text[:120]}...\")\n"]),

(C, ["# 3.3 Scoped search -- search within specific containers\n",
     "results = client.search.documents(\n",
     '    q="design systems and tools",\n',
     '    container_tags=["user_sarah"]\n',
     ")\n", "\n",
     "print(f\"Found {len(results.results)} results in user_sarah:\")\n",
     "for r in results.results[:5]:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n"]),

(C, ["# 3.4 Threshold tuning -- precision vs recall\n",
     "# document_threshold: 0.0-1.0 (higher = more precise, fewer results)\n", "\n",
     "print(\"=== High Precision (threshold=0.7) ===\")\n",
     "precise = client.search.documents(\n",
     '    q="distributed systems",\n',
     "    document_threshold=0.7,\n",
     "    limit=5\n",
     ")\n",
     "print(f\"Results: {len(precise.results)} (only highly relevant matches)\")\n", "\n",
     "print(\"=== High Recall (threshold=0.3) ===\")\n",
     "broad = client.search.documents(\n",
     '    q="distributed systems",\n',
     "    document_threshold=0.3,\n",
     "    limit=10\n",
     ")\n",
     "print(f\"Results: {len(broad.results)} (includes loosely related matches)\")\n", "\n",
     "print(\"Tip: 0.7+ for exact answers, 0.3-0.5 for exploratory searches\")\n"]),

(C, ["# 3.5 Pagination with offset and limit\n",
     "page_size = 3\n", "\n",
     "for page in range(3):  # Fetch up to 3 pages\n",
     "    results = client.search.documents(\n",
     '        q="engineering practices",\n',
     "        limit=page_size,\n",
     "        offset=page * page_size\n",
     "    )\n",
     "    if not results.results:\n",
     "        break\n",
     "    print(f\"--- Page {page + 1} ---\")\n",
     "    for r in results.results:\n",
     "        print(f\"  {r.get('memory', str(r))[:80]}...\")\n",
     "print(f\"\nDone paginating.\")\n"]),

(C, ["# 3.6 Fast search with onlyMatchingChunks\n",
     "# When you only need exact match snippets, skip full document context\n",
     "results = client.search.documents(\n",
     '    q="Python programming",\n',
     "    limit=5,\n",
     "    only_matching_chunks=True  # Faster, returns only relevant snippets\n",
     ")\n",
     "print(f\"Fast search ({len(results.results)} results):\")\n",
     "for r in results.results[:3]:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n"]),

(C, ["# 3.7 The profile() shortcut -- context + search in ONE call\n",
     "# This is the recommended pattern for chatbots and agents\n",
     "result = client.profile(\n",
     '    container_tag="user_sarah",\n',
     '    q="design tools and preferences"  # search query for relevant memories\n',
     ")\n", "\n",
     "print(\"=== Static Facts ===\")\n",
     "for fact in result.profile.static:\n",
     "    print(f\"  - {fact}\")\n",
     "print(f\"\n=== Dynamic Facts ===\")\n",
     "for fact in result.profile.dynamic:\n",
     "    print(f\"  - {fact}\")\n",
     "print(f\"\n=== Relevant Memories (from search) ===\")\n",
     "for r in result.search_results.results[:3]:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n", "\n",
     "print(\"\nOne call. ~50ms. Static + dynamic + search. All in one.\")\n"]),

(M, ["## 3.8 Search Best Practices\n", "\n",
     "- **Use `profile()` for chatbots** -- it combines context + search in one call\n",
     "- **Set `document_threshold`** -- 0.7+ for precise, 0.3-0.5 for exploratory\n",
     "- **Keep limits small** -- `limit=5` is usually enough; paginate for more\n",
     "- **Use `only_matching_chunks=True`** for speed when you don't need full context\n",
     "- **Always scope with container tags** -- tagless searches are slower and less relevant\n", "\n",
     "**Next:** Notebook 04 -- User Profiles\n"]),
])

# ============================================================
# NOTEBOOK 04: User Profiles
# ============================================================

save("04_user_profiles.ipynb", [

(M, ["# 04 -- User Profiles\n", "\n",
     "## What We'll Cover\n",
     "1. Static vs Dynamic profiles\n",
     "2. How profiles auto-build from ingestion\n",
     "3. Using profiles for LLM context injection\n",
     "4. Profile + Search combined (the recommended pattern)\n",
     "5. Use cases: chatbots, support, education, dev tools\n"]),

(M, ["## 4.1 Why Profiles?\n", "\n",
     "Traditional memory relies entirely on search. But search is too narrow -- "
     "when you search for \"project updates\", you miss that the user prefers bullet points, "
     "works in PST, and uses specific terminology.\n", "\n",
     "Profiles provide **the foundation**: a complete picture of who the user is -- "
     "always available, no search needed.\n", "\n",
     "**Performance:** Profile call: ~50ms | Search call: 200-500ms | "
     "Context retrieval: 1 call instead of 3-5 separate searches\n"]),

(M, ["## 4.2 Static vs Dynamic Profiles\n", "\n",
     "### Static Profile (Long-term, Stable Facts)\n",
     "- \"Sarah is a senior software engineer at TechCorp\"\n",
     "- \"Sarah specializes in distributed systems\"\n",
     "- \"Sarah prefers technical docs over video tutorials\"\n", "\n",
     "These persist until contradicted. Supermemory handles Updates automatically.\n", "\n",
     "### Dynamic Profile (Recent Context, Temporary States)\n",
     "- \"Sarah is migrating the payment service to microservices\"\n",
     "- \"Sarah is preparing for a conference talk next month\"\n",
     "- \"Sarah is debugging a memory leak in auth service\"\n", "\n",
     "These evolve as the user's context changes. Supermemory manages the lifecycle.\n"]),

(C, ["# 4.3 Basic profile retrieval\n",
     "from supermemory import Supermemory\n",
     "client = Supermemory()\n", "\n",
     "# Get profile without a search query (lightweight, ~30ms)\n",
     "profile = client.profile(container_tag=\"user_sarah\")\n", "\n",
     "print(\"=== STATIC PROFILE ===\")\n",
     "for fact in profile.profile.static:\n",
     "    print(f\"  * {fact}\")\n",
     "print(f\"\n=== DYNAMIC PROFILE ===\")\n",
     "for fact in profile.profile.dynamic:\n",
     "    print(f\"  * {fact}\")\n"]),

(C, ["# 4.4 Profile with search -- the recommended pattern\n",
     "# Combines user context + search results in ONE call\n",
     "result = client.profile(\n",
     '    container_tag="user_sarah",\n',
     '    q="What design tools does Sarah use?",  # search query\n',
     '    threshold=0.5  # relevance threshold\n',
     ")\n", "\n",
     "print(\"=== Static Facts (always available) ===\")\n",
     "for fact in result.profile.static:\n",
     "    print(f\"  * {fact}\")\n",
     "print(f\"\n=== Dynamic Facts (recent context) ===\")\n",
     "for fact in result.profile.dynamic:\n",
     "    print(f\"  * {fact}\")\n",
     "print(f\"\n=== Relevant Search Memories ===\")\n",
     "for r in result.search_results.results[:5]:\n",
     "    score = r.get(\"score\", \"N/A\")\n",
     "    memory = r.get(\"memory\", str(r))\n",
     "    print(f\"  [{score}] {memory[:100]}...\")\n"]),

(C, ["# 4.5 Building context for an LLM from a profile\n",
     "# THIS is the core pattern every chatbot/agent should use\n",
     "def build_llm_context(profile, user_name=\"User\"):\n",
     '    """Build a rich system prompt from a Supermemory profile."""\n',
     "    static = \"\n\".join(f\"- {f}\" for f in profile.profile.static)\n",
     "    dynamic = \"\n\".join(f\"- {f}\" for f in profile.profile.dynamic)\n",
     "    memories = \"\n\".join(\n",
     '        f"- {r.get(\"memory\", str(r))}"\n',
     "        for r in profile.search_results.results[:5]\n",
     "    )\n", "\n",
     "    return f\"\"\"You are assisting {user_name}.\n",
     "\n",
     "BACKGROUND (long-term facts):\n",
     "{static if static else 'No profile yet.'}\n",
     "\n",
     "CURRENT FOCUS (recent activity):\n",
     "{dynamic if dynamic else 'No recent context.'}\n",
     "\n",
     "RELEVANT PAST CONTEXT:\n",
     "{memories if memories else 'No relevant memories.'}\n",
     "\n",
     "Adjust responses to their expertise, preferences, and current work.\"\"\"\n", "\n",
     "# Example usage\n",
     'prompt = build_llm_context(result, user_name="Sarah")\n',
     "print(prompt)\n",
     "print(\"\n--- Now feed this system prompt to your LLM! ---\")\n"]),

(C, ["# 4.6 Profiles self-build -- just keep adding content\n",
     "# Add more conversations, profile updates automatically\n",
     "more_conversations = [\n",
     '    "user: I finished the dashboard! It uses a 12-column grid.\nassistant: Great!",\n',
     '    "user: I prefer dark mode for all my design tools.\nassistant: Noted.",\n',
     '    "user: The Figma component library needs accessibility updates.\nassistant: On it.",\n',
     "]\n", "\n",
     "for conv in more_conversations:\n",
     "    client.add(content=conv, container_tag=\"user_sarah\")\n",
     "    print(f\"Added: {conv.split(chr(10))[0]}...\")\n", "\n",
     "# Check updated profile\n",
     "updated = client.profile(container_tag=\"user_sarah\")\n",
     "print(f\"\nStatic facts: {len(updated.profile.static)}\")\n",
     "print(f\"Dynamic facts: {len(updated.profile.dynamic)}\")\n",
     "print(\"New facts have been extracted and merged into the profile!\")\n"]),

(M, ["## 4.7 Use Cases\n", "\n",
     "### Personalized AI Assistants\n",
     "Profiles provide: expertise level, communication preferences, tools used, current projects\n", "\n",
     "### Customer Support\n",
     "Profiles provide: product usage history, previous issues, tech proficiency\n",
     "No more \"let me look up your account\" -- agents immediately understand context\n", "\n",
     "### Educational Platforms\n",
     "Profiles provide: learning style, completed courses, strengths/weaknesses\n", "\n",
     "### Development Tools\n",
     "Profiles provide: preferred languages, coding style, current project context\n", "\n",
     "## 4.8 Key Takeaways\n", "\n",
     "- Profiles auto-build from ingestion -- zero manual management needed\n",
     "- Static = long-term stable facts, Dynamic = recent context\n",
     "- `profile(container_tag, q=...)` = context + search in one ~50ms call\n",
     "- Use profiles to build rich system prompts for LLMs\n", "\n",
     "**Next:** Notebook 05 -- Graph Memory & Relationships\n"]),
])

# ============================================================
# NOTEBOOK 05: Graph Memory & Relationships
# ============================================================

save("05_graph_memory_and_relationships.ipynb", [

(M, ["# 05 -- Graph Memory & Relationships\n", "\n",
     "## What We'll Cover\n",
     "1. The knowledge graph mental model\n",
     "2. Three relationship types: Updates, Extends, Derives\n",
     "3. How relationships form automatically\n",
     "4. Automatic forgetting and contradiction resolution\n",
     "5. Memory types: Facts, Preferences, Episodes\n"]),

(M, ["## 5.1 Not a Vector DB -- A Living Knowledge Graph\n", "\n",
     "Traditional vector databases store chunks independently with no connections. "
     "Supermemory builds a **graph** where memories connect to other memories through "
     "typed relationships. It's facts built on top of other facts.\n", "\n",
     "### Three Relationship Types\n", "\n",
     "**1. UPDATES -- Information Changes**\n",
     "When new info contradicts existing knowledge. The newer memory UPDATES the older one. "
     "The `isLatest` flag ensures searches return current information while preserving history.\n", "\n",
     "**2. EXTENDS -- Information Enriches**\n",
     "When new info adds detail without replacing. Both memories remain valid -- "
     "searches get richer context with both the base fact and the extension.\n", "\n",
     "**3. DERIVES -- Information Infers**\n",
     "The most sophisticated type: Supermemory infers new facts from patterns, "
     "surfacing insights you never explicitly stated.\n"]),

(C, ["# 5.2 Demo: 'Updates' relationship -- contradiction resolution\n",
     "from supermemory import Supermemory\n",
     "client = Supermemory()\n", "\n",
     "# Step 1: Add initial fact\n",
     "client.add(\n",
     '    content="Alex works at Google as a software engineer.",\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "print(\"Step 1: Alex works at Google\")\n", "\n",
     "# Step 2: Later, Alex changes jobs -- new info contradicts old\n",
     "# Supermemory creates an UPDATE relationship automatically\n",
     "client.add(\n",
     '    content="Alex just started at Stripe as a Product Manager.",\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "print(\"Step 2: Alex now works at Stripe (UPDATES previous fact)\")\n", "\n",
     "# Step 3: Query -- returns CURRENT info, not old info\n",
     "profile = client.profile(\n",
     '    container_tag="user_alex_work",\n',
     '    q="Where does Alex work?"\n',
     ")\n",
     "print(\"\n=== Profile after updates ===\")\n",
     "for fact in profile.profile.static:\n",
     "    print(f\"  * {fact}\")\n",
     "print(\"\nSUPERMEMORY tracked: Stripe is LATEST, Google is HISTORICAL.\")\n",
     "print(\"Both are preserved, but current info is returned by default.\")\n"]),

(C, ["# 5.3 Demo: 'Extends' relationship -- adding richness\n",
     "client.add(\n",
     '    content="Alex focuses on payments infrastructure and leads a team of 5.",\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "print(\"Added: Alex focuses on payments, leads team of 5\")\n",
     "print()\n",
     "print(\"This EXTENDS the fact 'Alex is a PM at Stripe'\")\n",
     "print(\"Both facts remain valid -- searches return richer, more complete context.\")\n"]),

(C, ["# 5.4 Demo: 'Derives' relationship -- inferred insights\n",
     "client.add(\n",
     '    content="Alex is a PM at Stripe.",\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "client.add(\n",
     '    content="Alex frequently discusses payment APIs, fraud detection, "\n',
     '             "and PCI compliance at work.",\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "print(\"Fact 1: Alex is a PM at Stripe\")\n",
     "print(\"Fact 2: Alex discusses payment APIs and fraud detection\")\n",
     "print()\n",
     "print(\"Supermemory may DERIVE: Alex likely works on core payments product.\")\n",
     "print(\"These are insights you never explicitly stated but are inferred.\")\n"]),

(C, ["# 5.5 Automatic forgetting -- time-based decay\n",
     "from datetime import datetime\n", "\n",
     "client.add(\n",
     '    content=f"My exam is scheduled for tomorrow.',\n',
     '    container_tag="user_alex_work"\n',
     ")\n",
     "print(\"Added time-sensitive fact: 'My exam is scheduled for tomorrow'\")\n",
     "print()\n",
     "print(\"After the exam date passes, this will be AUTOMATICALLY forgotten.\")\n",
     "print()\n",
     "print(\"Other auto-forgotten content examples:\")\n",
     "print(\"  'Meeting with Alex at 3pm today' -> forgotten after today\")\n",
     "print(\"  'I am at the airport' -> forgotten after some time\")\n",
     "print(\"  Casual, non-meaningful chatter -> never becomes permanent\")\n"]),

(C, ["# 5.6 Memory types -- Facts, Preferences, Episodes\n",
     "print(\"Supermemory distinguishes three memory types automatically:\")\n",
     "print()\n",
     "print(\"FACTS: Persist until updated or contradicted\")\n",
     "print('  Example: \"Alex is a PM at Stripe\"')\n",
     "print('  Example: \"The company was founded in 2020\"')\n",
     "print()\n",
     "print(\"PREFERENCES: Strengthen with repetition\")\n",
     "print('  Example: \"Alex prefers morning meetings\"')\n",
     "print('  Example: \"Alex likes functional programming\"')\n",
     "print()\n",
     "print(\"EPISODES: Decay over time unless significant\")\n",
     "print('  Example: \"Met Alex for coffee Tuesday\"')\n",
     "print('  Example: \"Alex mentioned a new project idea\"')\n",
     "print()\n",
     "print(\"ALL OF THIS IS AUTOMATIC. You never tag types or clean up.\")\n"]),

(M, ["## 5.7 What You NEVER Have to Do\n", "\n",
     "All of this is automatic. You never need to:\n",
     "- Define relationships manually\n",
     "- Tag memory types\n",
     "- Clean up old or expired memories\n",
     "- Resolve contradictions between facts\n",
     "- Manage knowledge versioning\n", "\n",
     "Just add content and search naturally. The graph maintains itself.\n", "\n",
     "**Next:** Notebook 06 -- Metadata & Advanced Filtering\n"]),
])

# ============================================================
# NOTEBOOK 06: Metadata & Advanced Filtering
# ============================================================

save("06_metadata_and_filtering.ipynb", [

(M, ["# 06 -- Metadata & Advanced Filtering\n", "\n",
     "## What We'll Cover\n",
     "1. Adding custom metadata to memories\n",
     "2. AND/OR compound filters\n",
     "3. Filtering search results by metadata\n",
     "4. Container-based organization strategies\n",
     "5. Filtered writes (context-aware ingestion)\n"]),

(C, ["# 6.1 Adding memories with rich metadata\n",
     "from supermemory import Supermemory\n",
     "client = Supermemory()\n", "\n",
     "# Metadata can be any key-value pairs: strings, numbers, booleans\n",
     "docs = [\n",
     "    {\n",
     '        "content": "Q4 revenue increased 23% YoY. Cloud services drove 60% of growth.",\n',
     '        "container_tag": "company_reports",\n',
     '        "metadata": {"category": "financial", "quarter": "Q4", "year": 2025, "priority": "high"}\n',
     "    },\n",
     "    {\n",
     '        "content": "New auth service to launch in Q3. Supports OAuth2 and SAML.",\n',
     '        "container_tag": "company_reports",\n',
     '        "metadata": {"category": "engineering", "status": "planned", "team": "platform"}\n',
     "    },\n",
     "    {\n",
     '        "content": "Hiring: 3 senior engineers for the ML platform team. Remote-friendly.",\n',
     '        "container_tag": "company_reports",\n',
     '        "metadata": {"category": "hr", "status": "open", "team": "ml-platform"}\n',
     "    },\n",
     "    {\n",
     '        "content": "Customer satisfaction score reached 94% in Q4, up from 91%.",\n',
     '        "container_tag": "company_reports",\n',
     '        "metadata": {"category": "financial", "quarter": "Q4", "year": 2025}\n',
     "    },\n",
     "]\n", "\n",
     "for doc in docs:\n",
     "    r = client.add(**doc)\n",
     "    print(f\"Added [{doc['metadata']['category']}]: {r.id}\")\n",
     "print(f\"\nTotal: {len(docs)} documents with structured metadata\")\n"]),

(C, ["# 6.2 Search with AND filters\n",
     "# Find financial documents from Q4 2025\n",
     "results = client.search.documents(\n",
     '    q="revenue growth",\n',
     '    container_tags=["company_reports"],\n',
     '    filters={\n',
     '        "AND": [\n',
     '            {"key": "category", "value": "financial"},\n',
     '            {"key": "year", "value": 2025}\n',
     '        ]\n',
     '    }\n',
     ")\n", "\n",
     "print(f\"Found {len(results.results)} financial docs from 2025:\")\n",
     "for r in results.results:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n"]),

(C, ["# 6.3 Search with OR filters\n",
     "# Find documents about engineering OR hr\n",
     "results = client.search.documents(\n",
     '    q="team updates",\n',
     '    container_tags=["company_reports"],\n',
     '    filters={\n',
     '        "OR": [\n',
     '            {"key": "category", "value": "engineering"},\n',
     '            {"key": "category", "value": "hr"}\n',
     '        ]\n',
     '    }\n',
     ")\n", "\n",
     "print(f\"Found {len(results.results)} engineering/hr documents:\")\n",
     "for r in results.results:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n"]),

(C, ["# 6.4 Combined AND/OR filters (nested)\n",
     "# (category=financial OR category=engineering) AND status=open\n",
     "results = client.search.documents(\n",
     '    q="",  # Empty query = return all matching filters\n',
     '    container_tags=["company_reports"],\n',
     '    filters={\n',
     '        "AND": [\n',
     '            {"OR": [\n',
     '                {"key": "category", "value": "financial"},\n',
     '                {"key": "category", "value": "engineering"}\n',
     '            ]},\n',
     '            {"key": "status", "value": "open"}\n',
     '        ]\n',
     '    }\n',
     ")\n",
     "print(f\"Results: {len(results.results)}\")\n",
     "print(\"Filter: (category=financial OR engineering) AND status=open\")\n",
     "for r in results.results:\n",
     "    print(f\"  - {r.get('memory', str(r))[:100]}...\")\n"]),

(C, ["# 6.5 Container tag organization strategies\n",
     "print(\"Container Tag Strategy Patterns:\")\n",
     "print()\n",
     "print(\"1. USER-SCOPED: container_tag = 'user_<id>'\")\n",
     "print(\"   Best for: chatbots, personal assistants, per-user profiles\")\n",
     "print()\n",
     "print(\"2. PROJECT-SCOPED: container_tag = 'project_<name>'\")\n",
     "print(\"   Best for: team projects, codebases, documentation\")\n",
     "print()\n",
     "print(\"3. MULTI-DIMENSIONAL: containerTags = ['user_X', 'project_Y', 'team_Z']\")\n",
     "print(\"   Best for: cross-cutting concerns, matrix organizations\")\n",
     "print()\n",
     "print(\"4. TENANT-SCOPED: Use userId for strict data isolation\")\n",
     "print(\"   Best for: multi-tenant SaaS, isolated customer data\")\n",
     "print()\n",
     "print(\"5. TEMPORAL: tags like 'sprint_42', 'quarter_q3'\")\n",
     "print(\"   Best for: time-bound projects, sprints, quarters\")\n"]),

(C, ["# 6.6 Filtered writes -- context-aware ingestion\n",
     "# filter_by_metadata: use only certain existing memories as context\n",
     "# when processing new content\n",
     "print(\"Filtered Write Pattern:\")\n",
     "print()\n",
     "print(\"When adding content about the ML platform,\")\n",
     "print(\"only use existing memories tagged with team='ml-platform' as context.\")\n",
     "print()\n",
     "print(\"client.add(\")\n",
     "print('    content=\"New ML model deployment pipeline is ready\",')\n",
     "print('    container_tag=\"company_reports\",')\n",
     "print('    filter_by_metadata={\"AND\": [{\"key\": \"team\", \"value\": \"ml-platform\"}]}')\n",
     "print(\")\")\n",
     "print()\n",
     "print(\"This ensures the new memory connects to the RIGHT existing context.\")\n"]),

(M, ["## 6.7 Key Takeaways\n", "\n",
     "- Metadata enables powerful filtering (AND, OR, nested combinations)\n",
     "- Container tags provide the primary scoping mechanism\n",
     "- Use `containerTags` for multi-dimensional organization\n",
     "- Filters work with search, list, and filtered writes\n",
     "- Organize early -- adding metadata retroactively is harder\n", "\n",
     "**Next:** Notebook 07 -- Async Operations\n"]),
])

# ============================================================
# NOTEBOOK 07: Async Operations
# ============================================================

save("07_async_operations.ipynb", [

(M, ["# 07 -- Async Operations\n", "\n",
     "## What We'll Cover\n",
     "1. AsyncSupermemory client\n",
     "2. Concurrent ingestion (parallel adds)\n",
     "3. Parallel profile lookups for multi-tenant apps\n",
     "4. Async file uploads\n",
     "5. Error handling in async mode\n",
     "6. Performance comparison: sync vs async\n"]),

(C, ["# 7.1 Sync vs Async Clients\n",
     "from supermemory import Supermemory, AsyncSupermemory\n",
     "import asyncio\n", "\n",
     "# Sync client (what we have used so far)\n",
     "sync_client = Supermemory()\n", "\n",
     "# Async client -- identical API, all methods are awaitable\n",
     "async_client = AsyncSupermemory()\n", "\n",
     "print(f\"Sync client: {type(sync_client).__name__}\")\n",
     "print(f\"Async client: {type(async_client).__name__}\")\n",
     "print(\"Functionality is identical. Only the calling pattern differs.\")\n"]),

(C, ["# 7.2 Basic async usage\n",
     "async def basic_async_example():\n",
     '    """Demonstrate basic async pattern."""\n',
     "    async with AsyncSupermemory() as client:\n",
     "        # Add a memory\n",
     "        response = await client.add(\n",
     '            content="Async operations are more efficient for bulk ingestion.",\n',
     '            container_tag="async_demo"\n',
     "        )\n",
     "        print(f\"Added: {response.id}\")\n", "\n",
     "        # Search\n",
     "        results = await client.search.execute(\n",
     '            q="async operations"\n',
     "        )\n",
     "        print(f\"Search results: {len(results.results)}\")\n", "\n",
     "# Run it\n",
     "asyncio.run(basic_async_example())\n"]),

(C, ["# 7.3 Concurrent ingestion -- the KILLER async feature\n",
     "# Process 20 documents in parallel, not sequentially\n",
     "import time\n", "\n",
     "async def concurrent_ingestion():\n",
     '    """Add 20 documents concurrently."""\n',
     "    async with AsyncSupermemory() as client:\n",
     "        docs = [\n",
     '            f"Document {i}: Content about topic {i} with details."\n',
     "            for i in range(20)\n",
     "        ]\n", "\n",
     "        # Launch ALL add operations concurrently\n",
     "        tasks = [\n",
     "            client.add(content=doc, container_tag=\"bulk_test\")\n",
     "            for doc in docs\n",
     "        ]\n",
     "        results = await asyncio.gather(*tasks)\n", "\n",
     "        print(f\"Ingested {len(results)} documents concurrently!\")\n",
     "        for r in results[:5]:\n",
     "            print(f\"  {r.id}: {r.status}\")\n",
     "        print(f\"  ... and {len(results) - 5} more\")\n",
     "        return results\n", "\n",
     "start = time.time()\n",
     "asyncio.run(concurrent_ingestion())\n",
     "print(f\"\nTime: {time.time() - start:.2f}s for 20 concurrent adds\")\n",
     "print(\"Sequential would take ~20x longer!\")\n"]),

(C, ["# 7.4 Parallel profile lookups -- perfect for multi-tenant apps\n",
     "async def parallel_profiles(user_ids):\n",
     '    """Look up profiles for multiple users in parallel."""\n',
     "    async with AsyncSupermemory() as client:\n",
     "        tasks = [\n",
     "            client.profile(container_tag=f\"user_{uid}\")\n",
     "            for uid in user_ids\n",
     "        ]\n",
     "        profiles = await asyncio.gather(*tasks)\n", "\n",
     "        for uid, profile in zip(user_ids, profiles):\n",
     "            static_n = len(profile.profile.static)\n",
     "            dynamic_n = len(profile.profile.dynamic)\n",
     "            print(f\"user_{uid}: {static_n} static, {dynamic_n} dynamic facts\")\n",
     "        return dict(zip(user_ids, profiles))\n", "\n",
     "asyncio.run(parallel_profiles([\"alex\", \"sarah\", \"alice\", \"bob\"]))\n"]),

(C, ["# 7.5 Async error handling with retries\n",
     "from supermemory import RateLimitError, APIConnectionError\n", "\n",
     "async def robust_add(client, content, container_tag, max_retries=3):\n",
     '    """Add memory with retry logic for transient errors."""\n',
     "    for attempt in range(max_retries):\n",
     "        try:\n",
     "            return await client.add(content=content, container_tag=container_tag)\n",
     "        except RateLimitError:\n",
     "            wait = 2 ** (attempt + 1)  # Exponential: 2, 4, 8 seconds\n",
     "            print(f\"Rate limited, retrying in {wait}s (attempt {attempt+1}/{max_retries})...\")\n",
     "            await asyncio.sleep(wait)\n",
     "        except APIConnectionError as e:\n",
     "            print(f\"Connection error: {e}, retrying...\")\n",
     "            await asyncio.sleep(1)\n",
     "    raise Exception(f\"Failed after {max_retries} attempts\")\n", "\n",
     "async def demo_robust():\n",
     "    async with AsyncSupermemory() as client:\n",
     "        r = await robust_add(client, \"Critical data that must be stored.\", \"critical\")\n",
     "        print(f\"Stored: {r.id}\")\n", "\n",
     "asyncio.run(demo_robust())\n"]),

(C, ["# 7.6 Async file upload\n",
     "from pathlib import Path\n", "\n",
     "async def async_file_upload():\n",
     "    async with AsyncSupermemory() as client:\n",
     "        # Upload file -- PathLike reads content asynchronously\n",
     "        # response = await client.documents.upload_file(\n",
     "        #     file=Path(\"/path/to/document.pdf\"),\n",
     "        #     container_tags=[\"user_001\"],\n",
     "        #     metadata={\"type\": \"report\"}\n",
     "        # )\n",
     "        # print(f\"Uploaded: {response.id}\")\n",
     "        print(\"Async file uploads work identically to sync -- just await them!\")\n", "\n",
     "asyncio.run(async_file_upload())\n"]),

(M, ["## 7.7 Performance Comparison\n", "\n",
     "| Operation | Sync (sequential) | Async (concurrent) |\n",
     "|-----------|-------------------|---------------------|\n",
     "| 1 document | ~100ms | ~100ms |\n",
     "| 10 documents | ~1000ms | ~150ms |\n",
     "| 100 documents | ~10s | ~500ms |\n",
     "| 10 user profiles | ~500ms | ~80ms |\n", "\n",
     "**Rule of thumb:** Use async when dealing with 3+ independent operations.\n", "\n",
     "**Next:** Notebook 08 -- Self-Hosting Supermemory\n"]),
])

# ============================================================
# NOTEBOOK 08: Self-Hosting Supermemory
# ============================================================

save("08_self_hosting.ipynb", [

(M, ["# 08 -- Self-Hosting Supermemory\n", "\n",
     "## What We'll Cover\n",
     "1. Installing the single binary\n",
     "2. Zero-config startup\n",
     "3. Bring-your-own-model (OpenAI, Anthropic, Ollama, etc.)\n",
     "4. Fully offline setup with Ollama\n",
     "5. Pointing SDKs to a local server\n",
     "6. Self-hosted vs Platform comparison\n"]),

(M, ["## 8.1 Why Self-Host?\n", "\n",
     "- **Free, open source** -- no API key needed, no usage limits\n",
     "- **Privacy** -- your data never leaves your machine\n",
     "- **Air-gapped** -- works fully offline with local models\n",
     "- **Same API** -- drop-in compatible with the hosted platform\n",
     "- **One binary** -- no Docker, no database to provision, no config files\n"]),

(C, ["# 8.2 Installation -- one command\n",
     "print(\"Install and start the server:\")\n",
     "print()\n",
     "print(\"Option A: Install script\")\n",
     "print(\"  curl -fsSL https://supermemory.ai/install | bash\")\n",
     "print()\n",
     "print(\"Option B: npx (Node.js required)\")\n",
     "print(\"  npx supermemory local\")\n",
     "print()\n",
     "print(\"On first boot, you get:\")\n",
     "print(\"  - Embedded graph engine (created automatically)\")\n",
     "print(\"  - Built-in local embeddings (nothing sent externally)\")\n",
     "print(\"  - Auto-generated API key (printed to console)\")\n",
     "print(\"  - Full Memory API at http://localhost:6767\")\n"]),

(C, ["# 8.3 Connecting SDK to local server -- one line change\n",
     "from supermemory import Supermemory\n", "\n",
     "# Point to your local server\n",
     "client = Supermemory(\n",
     '    api_key="sm_local_key",  # printed on first boot\n',
     '    base_url="http://localhost:6767"\n',
     ")\n", "\n",
     "print(\"Connected to local Supermemory server!\")\n",
     "print(\"\nAll methods work identically:\")\n",
     "print(\"  client.add(...)\")\n",
     "print(\"  client.profile(...)\")\n",
     "print(\"  client.search.documents(...)\")\n",
     "print(\"  client.documents.list(...)\")\n",
     "print()\n",
     "print(\"AI coding plugins (Claude Code, Codex, OpenCode) also work:\")\n",
     "print('  export SUPERMEMORY_API_URL=http://localhost:6767')\n"]),

(C, ["# 8.4 Bring your own model\n",
     "print(\"Supermemory needs an LLM for memory extraction.\")\n",
     "print(\"You can bring ANY provider:\")\n",
     "print()\n",
     "print(\"OpenAI:\")\n",
     "print('  OPENAI_API_KEY=sk-... OPENAI_MODEL=gpt-4o supermemory-server')\n",
     "print()\n",
     "print(\"Anthropic:\")\n",
     "print('  ANTHROPIC_API_KEY=sk-ant-... ANTHROPIC_MODEL=claude-sonnet-4-6 supermemory-server')\n",
     "print()\n",
     "print(\"Gemini:\")\n",
     "print('  GEMINI_API_KEY=... GEMINI_MODEL=gemini-2.5-pro supermemory-server')\n",
     "print()\n",
     "print(\"Groq:\")\n",
     "print('  GROQ_API_KEY=... GROQ_MODEL=llama-4-maverick supermemory-server')\n",
     "print()\n",
     "print(\"Any OpenAI-compatible endpoint works.\")\n"]),

(C, ["# 8.5 Fully offline with Ollama\n",
     "print(\"For a fully offline setup (no internet after download):\")\n",
     "print()\n",
     "print(\"1. Install Ollama: curl -fsSL https://ollama.ai/install.sh | sh\")\n",
     "print(\"2. Pull a model: ollama pull qwen3:32b\")\n",
     "print(\"3. Start Supermemory pointing to Ollama:\")\n",
     "print()\n",
     "print('  OPENAI_BASE_URL=http://localhost:11434/v1 \\\\')\n",
     "print('  OPENAI_API_KEY=ollama \\\\')\n",
     "print('  OPENAI_MODEL=qwen3:32b \\\\')\n",
     "print('  supermemory-server')\n",
     "print()\n",
     "print(\"Now everything is local:\")\n",
     "print(\"  Graph engine -> on your machine\")\n",
     "print(\"  Embeddings -> computed locally\")\n",
     "print(\"  LLM -> Ollama (local)\")\n",
     "print(\"  Your data NEVER leaves your machine.\")\n"]),

(C, ["# 8.6 Self-hosted vs Platform comparison\n",
     "features = [\n",
     '    ("Full Memory API", "Yes", "Yes"),\n',
     '    ("Hybrid semantic search", "Yes", "Yes"),\n',
     '    ("Local embeddings", "On your machine", "Managed"),\n',
     '    ("File ingestion (PDFs, images)", "Yes", "Yes"),\n',
     '    ("Connectors (GDrive, Notion, etc.)", "No", "Yes"),\n',
     '    ("MCP Server", "No", "Yes"),\n',
     '    ("Extraction quality", "Your model", "Proprietary (best)"),\n',
     '    ("Cost", "Free", "Freemium"),\n',
     '    ("Infrastructure", "Your machine", "Globally distributed"),\n',
     "]\n", "\n",
     "print(f\"{'Feature':<35} {'Self-hosted':<20} {'Platform':<20}\")\n",
     "print(\"-\" * 75)\n",
     "for name, self_h, plat in features:\n",
     "    print(f\"{name:<35} {self_h:<20} {plat:<20}\")\n",
     "print()\n",
     "print(\"Best of both worlds: develop locally, deploy on platform with one base_url change.\")\n"]),

(M, ["## 8.7 Key Takeaways\n", "\n",
     "- Self-hosting is a single binary -- `curl ... | bash` and you are running\n",
     "- Zero config: embedded database, auto-generated API key, built-in embeddings\n",
     "- Bring any model: OpenAI, Anthropic, Gemini, Groq, or local with Ollama\n",
     "- Fully offline possible: Ollama + Supermemory = local graph engine + local LLM\n",
     "- SDK code is identical -- just change `base_url`\n", "\n",
     "**Next:** Notebook 09 -- Integrating with LLMs\n"]),
])

# ============================================================
# NOTEBOOK 09: Integrating with LLMs
# ============================================================

save("09_integrating_with_llms.ipynb", [

(M, ["# 09 -- Integrating with LLMs\n", "\n",
     "## What We'll Cover\n",
     "1. The chatbot with memory pattern\n",
     "2. Agent memory workflow\n",
     "3. RAG with Supermemory\n",
     "4. OpenAI integration example\n",
     "5. Vercel AI SDK integration\n",
     "6. Multi-turn conversation management\n"]),

(M, ["## 9.1 The Core Pattern: Profile -> Chat -> Store\n", "\n",
     "Every LLM integration follows the same three-step pattern:\n", "\n",
     "1. **Profile**: Get user context before the LLM call (~50ms)\n",
     "2. **Chat**: Inject profile into system prompt, call LLM with enriched context\n",
     "3. **Store**: Save the conversation for future context\n", "\n",
     "This ensures every conversation is personalized AND improves over time.\n"]),

(C, ["# 9.2 Complete chatbot with memory pattern\n",
     "from supermemory import Supermemory\n", "\n",
     "class MemoryChatbot:\n",
     '    """A chatbot that remembers users across conversations."""\n', "\n",
     '    def __init__(self, user_id: str):\n',
     "        self.sm = Supermemory()\n",
     "        self.user_id = user_id\n",
     "        self.container_tag = f\"user_{user_id}\"\n",
     "        self.history = []\n", "\n",
     '    def _build_system_prompt(self, user_message: str) -> str:\n',
     '        """Build enriched system prompt from user profile."""\n',
     "        try:\n",
     "            profile = self.sm.profile(\n",
     "                container_tag=self.container_tag,\n",
     "                q=user_message\n",
     "            )\n",
     "            static = \"\n\".join(f\"- {f}\" for f in profile.profile.static)\n",
     "            dynamic = \"\n\".join(f\"- {f}\" for f in profile.profile.dynamic)\n",
     "            memories = \"\n\".join(\n",
     '                f"- {r.get(\"memory\", str(r))}"\n',
     "                for r in profile.search_results.results[:5]\n",
     "            )\n",
     "            return f\"\"\"You are a helpful, personalized assistant.\n",
     "\n",
     "User Profile (long-term):\n",
     "{static if static else 'No profile yet.'}\n",
     "\n",
     "Current Context (recent):\n",
     "{dynamic if dynamic else 'No recent context.'}\n",
     "\n",
     "Relevant Memories:\n",
     "{memories if memories else 'No relevant memories.'}\n",
     "\n",
     "Use this context to personalize your responses.\"\"\"\n",
     "        except Exception as e:\n",
     '            return "You are a helpful assistant."  # graceful fallback\n', "\n",
     '    def chat(self, user_message: str) -> str:\n',
     '        """Process a message and return a response."""\n',
     "        system_prompt = self._build_system_prompt(user_message)\n",
     "        # In production, call your LLM here with system_prompt\n",
     "        # response = openai.chat.completions.create(\n",
     "        #     model=\"gpt-4o\",\n",
     "        #     messages=[\n",
     '        #         {"role": "system", "content": system_prompt},\n',
     "        #         *self.history[-10:],\n",
     '        #         {"role": "user", "content": user_message}\n',
     "        #     ]\n",
     "        # )\n",
     '        response_text = "[LLM response would appear here, enriched with profile]"\n', "\n",
     "        # Store the conversation turn\n",
     "        conv = f\"user: {user_message}\nassistant: {response_text}\"\n",
     "        self.sm.add(content=conv, container_tag=self.container_tag)\n",
     "        self.history.append({\"role\": \"user\", \"content\": user_message})\n",
     "        self.history.append({\"role\": \"assistant\", \"content\": response_text})\n",
     "        return response_text\n", "\n",
     "# Demo\n",
     'bot = MemoryChatbot(user_id="sarah")\n',
     'print("Chatbot initialized for user: sarah")\n',
     'response = bot.chat("Can you help me design a dashboard?")\n',
     'print(f"User: Can you help me design a dashboard?")\n',
     'print(f"Bot: {response}")\n',
     "print()\n",
     "print(\"System prompt was enriched with Sarah's profile (designer, Figma, etc.)\")\n"]),

(C, ["# 9.3 Agent memory pattern\n",
     "class MemoryAgent:\n",
     '    """An agent that uses Supermemory for persistent task memory."""\n', "\n",
     '    def __init__(self, agent_name: str):\n',
     "        self.sm = Supermemory()\n",
     "        self.agent_name = agent_name\n",
     "        self.container_tag = f\"agent_{agent_name}\"\n", "\n",
     '    def get_context(self, task: str) -> str:\n',
     "        profile = self.sm.profile(container_tag=self.container_tag, q=task)\n",
     "        facts = profile.profile.static + profile.profile.dynamic\n",
     '        memories = [r.get(\"memory\", str(r)) for r in profile.search_results.results[:3]]\n',
     '        return "\n".join(f"- {x}" for x in facts + memories)\n', "\n",
     '    def record_result(self, task: str, result: str, success: bool):\n',
     '        status = "SUCCESS" if success else "FAILED"\n',
     "        content = f\"TASK: {task}\nRESULT ({status}): {result}\"\n",
     "        self.sm.add(content=content, container_tag=self.container_tag,\n",
     '                     metadata={\"type\": \"task_result\", \"success\": success})\n', "\n",
     '    def record_preference(self, preference: str):\n',
     "        self.sm.add(content=f\"PREFERENCE: {preference}\",\n",
     '                     container_tag=self.container_tag, metadata={\"type\": \"preference\"})\n', "\n",
     "# Demo\n",
     'agent = MemoryAgent(agent_name="devops_bot")\n',
     'agent.record_preference("User prefers deployments on Tuesdays at 10am PST")\n',
     'agent.record_result("Deploy v2.3 to staging", "All tests passed, no regressions", True)\n',
     'agent.record_result("Database migration", "Failed: lock timeout on users table", False)\n',
     "print(\"Agent memory recorded:\")\n",
     "print(\"  - Preference: Tuesday 10am deployments\")\n",
     "print(\"  - Task: Deploy v2.3 staging -> SUCCESS\")\n",
     "print(\"  - Task: Database migration -> FAILED\")\n",
     "print()\n",
     'ctx = agent.get_context("deploy new version")\n',
     'print("Context for 'deploy new version':")\n',
     "print(ctx)\n"]),

(C, ["# 9.4 RAG with Supermemory\n",
     "class SupermemoryRAG:\n",
     '    """RAG pipeline backed by Supermemory."""\n', "\n",
     '    def __init__(self, kb_name: str = "default_kb"):\n',
     "        self.sm = Supermemory()\n",
     "        self.kb_tag = f\"kb_{kb_name}\"\n", "\n",
     '    def ingest(self, content: str, metadata: dict = None):\n',
     "        return self.sm.add(content=content, container_tag=self.kb_tag,\n",
     "                            metadata=metadata or {})\n", "\n",
     '    def retrieve(self, query: str, top_k: int = 5) -> list:\n',
     "        results = self.sm.search.documents(\n",
     "            q=query, container_tags=[self.kb_tag],\n",
     "            limit=top_k, document_threshold=0.5\n",
     "        )\n",
     '        return [r.get("memory", str(r)) for r in results.results]\n', "\n",
     "# Demo: build a company knowledge base\n",
     'rag = SupermemoryRAG(kb_name="company")\n',
     'rag.ingest("Our company was founded in 2020. We build AI developer tools.")\n',
     'rag.ingest("We have 50 employees across 12 countries. Remote-first culture.")\n',
     'rag.ingest("Our flagship product, CodeAssist, is an AI coding companion.")\n', "\n",
     'chunks = rag.retrieve("tell me about the company")\n',
     'print("Retrieved chunks:")\n',
     "for i, chunk in enumerate(chunks, 1):\n",
     "    print(f\"  {i}. {chunk[:100]}...\")\n"]),

(C, ["# 9.5 Framework integrations\n",
     "print(\"Supermemory integrates with all major AI frameworks:\")\n",
     "print()\n",
     "print(\"Vercel AI SDK (TypeScript):\")\n",
     "print('  import { withSupermemory } from \"@supermemory/tools/ai-sdk\";')\n",
     '  print(\'  const model = withSupermemory(openai(\"gpt-4o\"), { containerTag: \"user_123\" });\')\n',
     "print()\n",
     "print(\"Mastra (TypeScript):\")\n",
     "print('  import { withSupermemory } from \"@supermemory/tools/mastra\";')\n",
     "print()\n",
     "print(\"LangChain: Community integration available\")\n",
     "print()\n",
     "print(\"MCP Server (Claude Desktop, Cursor, Windsurf, VS Code):\")\n",
     "print(\"  npx -y install-mcp@latest https://mcp.supermemory.ai/mcp --client claude\")\n",
     "print()\n",
     "print(\"AI Coding Agents (plugins):\")\n",
     "print(\"  Claude Code: claude-supermemory plugin\")\n",
     "print(\"  Codex CLI: codex-supermemory plugin\")\n",
     "print(\"  OpenCode: opencode-supermemory plugin\")\n",
     "print(\"  Hermes: Native skill\")\n"]),

(M, ["## 9.6 Best Practices for LLM Integration\n", "\n",
     "1. **Profile before every LLM call** -- it is fast (~50ms) and dramatically improves quality\n",
     "2. **Store after every exchange** -- conversations are the fuel for better profiles\n",
     "3. **Use customId for conversations** -- enables incremental updates without duplication\n",
     "4. **Limit memory injection** -- 3-5 most relevant memories, not everything\n",
     "5. **Handle profile failures gracefully** -- fall back to a generic system prompt\n",
     "6. **Use profile() with q= parameter** -- combines context + search in one call\n", "\n",
     "**Next:** Notebook 10 -- Production Patterns\n"]),
])

# ============================================================
# NOTEBOOK 10: Production Patterns
# ============================================================

save("10_production_patterns.ipynb", [

(M, ["# 10 -- Production Patterns\n", "\n",
     "## What We'll Cover\n",
     "1. Error handling and retries\n",
     "2. Timeout configuration\n",
     "3. Rate limiting strategies\n",
     "4. Caching profiles\n",
     "5. Logging and monitoring\n",
     "6. Testing strategies\n",
     "7. Production deployment checklist\n"]),

(C, ["# 10.1 Comprehensive error handling\n",
     "from supermemory import (\n",
     "    Supermemory, APIError, APIConnectionError, APIStatusError,\n",
     "    AuthenticationError, RateLimitError, PermissionDeniedError,\n",
     "    NotFoundError, BadRequestError, UnprocessableEntityError,\n",
     "    InternalServerError\n",
     ")\n",
     "import time\n", "\n",
     "class RobustClient:\n",
     '    """Production-ready wrapper with error handling."""\n', "\n",
     '    def __init__(self, max_retries: int = 3, base_delay: float = 1.0):\n',
     "        self.client = Supermemory()\n",
     "        self.max_retries = max_retries\n",
     "        self.base_delay = base_delay\n", "\n",
     '    def add_with_retry(self, content: str, container_tag: str, **kwargs):\n',
     "        for attempt in range(self.max_retries + 1):\n",
     "            try:\n",
     "                return self.client.add(content=content, container_tag=container_tag, **kwargs)\n",
     "            except RateLimitError:\n",
     "                if attempt == self.max_retries: raise\n",
     "                delay = self.base_delay * (2 ** attempt)\n",
     "                print(f\"Rate limited. Retrying in {delay}s...\")\n",
     "                time.sleep(delay)\n",
     "            except APIConnectionError:\n",
     "                if attempt == self.max_retries: raise\n",
     "                print(f\"Connection error. Retrying...\")\n",
     "                time.sleep(self.base_delay * (2 ** attempt))\n",
     "            except (BadRequestError, UnprocessableEntityError, AuthenticationError,\n",
     "                    PermissionDeniedError, NotFoundError) as e:\n",
     "                print(f\"Client error (not retrying): {type(e).__name__}\")\n",
     "                raise\n",
     "            except InternalServerError:\n",
     "                if attempt == self.max_retries: raise\n",
     "                print(\"Server error. Retrying...\")\n",
     "                time.sleep(self.base_delay * (2 ** attempt))\n", "\n",
     "robust = RobustClient()\n",
     "print(\"Robust client ready with error handling:\")\n",
     "print(\"  Rate limits: exponential backoff (1s, 2s, 4s)\")\n",
     "print(\"  Connection errors: retry with backoff\")\n",
     "print(\"  Client errors (400, 422, 401, 403, 404): fast fail, no retry\")\n",
     "print(\"  Server errors (500+): retry with backoff\")\n"]),

(C, ["# 10.2 Timeout configuration for different workloads\n",
     "import httpx\n", "\n",
     "# Fast operations: search, profile (sub-300ms)\n",
     "fast_client = Supermemory(timeout=10.0)\n", "\n",
     "# Slow operations: file uploads, URL extraction (1-10 min)\n",
     "slow_client = Supermemory(\n",
     "    timeout=httpx.Timeout(600.0, connect=10.0, read=300.0, write=60.0)\n",
     ")\n", "\n",
     "print(\"Timeout strategies:\")\n",
     "print(\"  Search/Profile: 10s (normally <1s)\")\n",
     "print(\"  File upload: 600s (large files need time)\")\n",
     "print(\"  URL extraction: 300s (page fetch + processing)\")\n",
     "print(\"  Use with_options() for per-call overrides\")\n"]),

(C, ["# 10.3 Profile caching for high-throughput apps\n",
     "from datetime import datetime, timedelta\n", "\n",
     "class CachedProfileService:\n",
     '    """Cache user profiles to reduce API calls."""\n', "\n",
     '    def __init__(self, ttl_seconds: int = 60):\n',
     "        self.client = Supermemory()\n",
     "        self.ttl = ttl_seconds\n",
     "        self._cache = {}  # {tag: (profile, cached_at)}\n", "\n",
     '    def get_profile(self, container_tag: str, query: str = None):\n',
     "        now = datetime.now()\n",
     "        if container_tag in self._cache:\n",
     "            cached, cached_at = self._cache[container_tag]\n",
     "            if (now - cached_at).total_seconds() < self.ttl:\n",
     "                print(f\"Cache HIT for {container_tag}\")\n",
     "                return cached\n",
     "        print(f\"Cache MISS for {container_tag}\")\n",
     "        profile = self.client.profile(container_tag=container_tag, q=query)\n",
     "        self._cache[container_tag] = (profile, now)\n",
     "        return profile\n", "\n",
     "cache = CachedProfileService(ttl_seconds=30)\n",
     'p1 = cache.get_profile("user_sarah")  # Cache MISS\n',
     'p1 = cache.get_profile("user_sarah")  # Cache HIT (within 30s)\n',
     "print()\n",
     "print(\"Caching is critical for:\")\n",
     "print(\"  - High-throughput chatbots (100+ concurrent users)\")\n",
     "print(\"  - API endpoints that call profile() on every request\")\n",
     "print(\"  Trade-off: cached profiles may be slightly stale\")\n"]),

(C, ["# 10.4 Logging and monitoring\n",
     "import os\n",
     "import logging\n", "\n",
     "# Enable SDK logging\n",
     'os.environ["SUPERMEMORY_LOG"] = "info"\n', "\n",
     "logging.basicConfig(\n",
     "    level=logging.INFO,\n",
     '    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"\n',
     ")\n",
     "logger = logging.getLogger(\"myapp.supermemory\")\n", "\n",
     "class MonitoredClient:\n",
     '    """Client wrapper with instrumentation."""\n',
     '    def __init__(self):\n',
     "        self.client = Supermemory()\n",
     '        self.stats = {"adds": 0, "searches": 0, "profiles": 0, "errors": 0}\n', "\n",
     '    def add(self, *args, **kwargs):\n',
     "        try:\n",
     "            result = self.client.add(*args, **kwargs)\n",
     '            self.stats["adds"] += 1\n',
     "            logger.info(f\"add() success: id={result.id}\")\n",
     "            return result\n",
     "        except Exception as e:\n",
     '            self.stats["errors"] += 1\n',
     "            logger.error(f\"add() failed: {e}\")\n",
     "            raise\n", "\n",
     "    def report(self):\n",
     "        print(\"Usage Report:\")\n",
     "        for k, v in self.stats.items():\n",
     "            print(f\"  {k}: {v}\")\n", "\n",
     "monitored = MonitoredClient()\n",
     "print(\"Monitored client ready with logging + stats tracking.\")\n"]),

(C, ["# 10.5 Testing strategies\n",
     "print(\"Testing Your Supermemory Integration:\")\n",
     "print()\n",
     "print(\"1. UNIT TESTS (mock the SDK)\")\n",
     "print(\"   from unittest.mock import patch, MagicMock\")\n",
     "print(\"   @patch('supermemory.Supermemory')\")\n",
     "print(\"   def test_chatbot_context(mock_sm): ...\")\n",
     "print()\n",
     "print(\"2. INTEGRATION TESTS (use self-hosted in CI)\")\n",
     "print(\"   npx supermemory local &\")\n",
     "print(\"   # Run tests against localhost:6767\")\n",
     "print()\n",
     "print(\"3. CONTRACT TESTS (verify API shape)\")\n",
     "print(\"   r = client.add(content='test', container_tag='test')\")\n",
     "print(\"   assert r.id is not None\")\n",
     "print(\"   assert r.status in ('queued', 'done')\")\n",
     "print()\n",
     "print(\"4. PERFORMANCE TESTS\")\n",
     "print(\"   start = time.time()\")\n",
     "print(\"   client.profile(container_tag='test')\")\n",
     "print(\"   assert time.time() - start < 1.0  # Under 1 second\")\n"]),

(M, ["## 10.6 Production Deployment Checklist\n", "\n",
     "**Security:**\n",
     "- [ ] API keys in environment variables, never in source code\n",
     "- [ ] Use separate API keys for dev / staging / production\n",
     "- [ ] Rotate API keys on a schedule\n", "\n",
     "**Reliability:**\n",
     "- [ ] Retry logic with exponential backoff for transient errors\n",
     "- [ ] Appropriate timeouts for each operation type\n",
     "- [ ] Profile caching for high-throughput scenarios (30-60s TTL)\n",
     "- [ ] Graceful degradation if Supermemory is unavailable\n", "\n",
     "**Performance:**\n",
     "- [ ] Use `profile()` with `q=` parameter (single call)\n",
     "- [ ] Limit search results to 3-5 items for context injection\n",
     "- [ ] Use `only_matching_chunks=True` for speed-critical searches\n",
     "- [ ] Async for concurrent operations (3+ independent calls)\n", "\n",
     "**Observability:**\n",
     "- [ ] Log all API errors with full context\n",
     "- [ ] Track latency percentiles (p50, p95, p99)\n",
     "- [ ] Monitor rate limit usage\n",
     "- [ ] Set up alerts for error rate spikes\n", "\n",
     "## 10.7 Key Takeaways\n", "\n",
     "- Handle errors by type: retry server errors, fail fast on client errors\n",
     "- Cache profiles for high-throughput apps (30-60s TTL)\n",
     "- Use self-hosted Supermemory for CI/testing to avoid consuming API quota\n",
     "- Always have a fallback path when memory is unavailable\n",
     "- Monitor: you cannot improve what you cannot measure\n"]),
])

print("\nDone! All 10 notebooks generated.")
