#!/usr/bin/env python3
"""Generate ADK tutorial notebooks with deep theory + heavily commented code."""
import json, os

BASE = r"C:\Users\guhar\ws\calude_tutorial\google_adk"
ENV_PATH = r"C:\Users\guhar\ws\calude_tutorial\google_adk\.env"

def nb(cells):
    """Build a notebook from list of (type, lines)."""
    out = []
    for ct, src in cells:
        if isinstance(src, str):
            src = [src]
        entry = {"cell_type": ct, "metadata": {}, "source": src}
        if ct == "code":
            entry["outputs"] = []
            entry["execution_count"] = None
        out.append(entry)
    return {
        "cells": out,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12.0"}
        },
        "nbformat": 4, "nbformat_minor": 4
    }

def save(name, cells):
    with open(os.path.join(BASE, name), 'w', encoding='utf-8') as f:
        json.dump(nb(cells), f, indent=1, ensure_ascii=False)

# ═══════════════════════════════════════════════════════════════════
# SHARED SNIPPETS
# ═══════════════════════════════════════════════════════════════════

ENV_LOAD = [
    '# ─── Load API key from .env file ───────────────────────────────────\n',
    '# Google ADK needs GOOGLE_API_KEY to call Gemini models.\n',
    '# The .env file (in this directory) stores your key safely.\n',
    '# This cell reads it and sets the environment variable for the session.\n',
    'import os\n',
    '_env_path = r"' + ENV_PATH + '"\n',
    'if os.path.exists(_env_path):\n',
    '    with open(_env_path) as f:\n',
    '        for line in f:\n',
    '            line = line.strip()\n',
    '            # Parse KEY=VALUE lines, skip comments and blanks\n',
    '            if line and "=" in line and not line.startswith("#"):\n',
    '                key, val = line.split("=", 1)\n',
    '                os.environ[key] = val.strip().strip(\'"\').strip("\'")\n',
    'has_key = bool(os.environ.get("GOOGLE_API_KEY", ""))\n',
    'print(f\'API key: {"✅ LOADED" if has_key else "❌ NOT FOUND — create .env file"}\')\n',
]

IMPORTS_BASE = [
    '# ─── Core ADK imports for every project ────────────────────────────\n',
    '# ADK 2.x uses a clean import structure. Here are the four essentials:\n',
    'import asyncio  # Required: session creation is async in ADK 2.x\n',
    'from google.adk import Agent  # The core agent class — your building block\n',
    'from google.adk.runners import Runner  # Executes agents and manages sessions\n',
    'from google.adk.sessions.in_memory_session_service import InMemorySessionService  # Stores conversation state\n',
    'from google.genai.types import Content, Part  # Message types (NOTE: google.genai.types, NOT google.adk.types!)\n',
    'print("✅ Core imports ready")\n',
]

# ═══════════════════════════════════════════════════════════════════
# NOTEBOOK 01
# ═══════════════════════════════════════════════════════════════════

save('01_installation_setup.ipynb', [
    # ── TITLE ──
    ("markdown", [
        "# Google ADK Tutorial — Part 1: Installation & Setup\n",
        "\n",
        "## What You'll Learn\n",
        "- What Google ADK is and why it exists\n",
        "- How to install and configure ADK\n",
        "- The architecture of an ADK application\n",
        "- Run your first agent (programmatically, not via CLI)\n",
        "\n",
        "> **Target version:** ADK 2.3.x (June 2026)\n",
    ]),

    # ── THEORY: What is ADK? ──
    ("markdown", [
        "## 1.1 What is Google ADK?\n",
        "\n",
        "**ADK (Agent Development Kit)** is Google's open-source framework for\n",
        "building AI agents. An *agent* is an LLM-powered program that can use\n",
        "tools (web search, code execution, APIs), maintain conversation state,\n",
        "and collaborate with other agents.\n",
        "\n",
        "### Why ADK instead of raw Gemini API?\n",
        "\n",
        "| Raw Gemini API | ADK |\n",
        "|---|---|\n",
        "| You manage conversation history manually | Automatic session management |\n",
        "| Tool calling requires manual loop | Built-in tool execution loop |\n",
        "| One model, one call | Multi-agent orchestration |\n",
        "| No state persistence | Session state + memory service |\n",
        "| No streaming infrastructure | Streaming events out of the box |\n",
        "| No deployment story | `adk deploy cloud_run` |\n",
        "\n",
        "### Core Architecture\n",
        "\n",
        "```\n",
        "┌─────────────────────────────────────────────────┐\n",
        "│                    Runner                        │\n",
        "│  ┌─────────┐   ┌──────────┐   ┌─────────────┐  │\n",
        "│  │  Agent   │──▶│  Session  │◀──│  Memory Svc  │  │\n",
        "│  │ (LLM +   │   │ (state,   │   │ (cross-      │  │\n",
        "│  │  tools)  │   │  history) │   │  session)    │  │\n",
        "│  └─────────┘   └──────────┘   └─────────────┘  │\n",
        "└─────────────────────────────────────────────────┘\n",
        "```\n",
        "\n",
        "- **Agent**: The \"brain\" — an LLM with instructions and tools\n",
        "- **Runner**: The execution engine that runs the agent loop\n",
        "- **Session**: Stores conversation history within a session (a session = a chat)\n",
        "- **Memory Service**: Stores facts across sessions (user preferences, etc.)\n",
    ]),

    # ── THEORY: Models and providers ──
    ("markdown", [
        "### Models and Providers\n",
        "\n",
        "ADK is **model-agnostic**. You can use:\n",
        "- **Gemini** (default) — requires `GOOGLE_API_KEY`\n",
        "- **Any LiteLLM model** — OpenAI, Anthropic, OpenRouter, Ollama, etc.\n",
        "\n",
        "Set the model when creating an agent:\n",
        "```python\n",
        "Agent(model='gemini-2.5-flash')           # Google Gemini (default)\n",
        "Agent(model='gpt-4o')                     # OpenAI\n",
        "Agent(model='openrouter:deepseek/deepseek-v3')  # OpenRouter → 200+ models\n",
        "Agent(model='ollama/llama3.2')            # Local Ollama\n",
        "```\n",
        "\n",
        "### The Agent Loop (How ADK Works Internally)\n",
        "\n",
        "When you call `runner.run()`, ADK executes this loop:\n",
        "\n",
        "```\n",
        "1. Send user message + conversation history to LLM\n",
        "2. LLM responds with either:\n",
        "   a) Text → return to user, DONE\n",
        "   b) Tool call → execute the tool, feed result back to LLM, GOTO 1\n",
        "3. Repeat until LLM produces text (not a tool call)\n",
        "```\n",
        "\n",
        "This is the **ReAct (Reasoning + Acting) pattern** — the agent reasons\n",
        "about what to do, acts via tools, and reasons about the results.\n",
    ]),

    # ── CHECK PYTHON ──
    ("code", [
        '# ─── Verify Python version ───────────────────────────────────────\n',
        '# ADK 2.x requires Python 3.11+ (uses modern typing features)\n',
        'import sys\n',
        'print(f"Python version: {sys.version}")\n',
        'assert sys.version_info >= (3, 11), "ADK 2.x needs Python 3.11+"\n',
        'print("✅ Python version OK")\n',
    ]),

    # ── CHECK ADK ──
    ("code", [
        '# ─── Verify ADK is installed ─────────────────────────────────────\n',
        '# The importlib.metadata module reads package versions from pip\n',
        'from importlib.metadata import version\n',
        'try:\n',
        '    adk_ver = version("google-adk")  # Query installed version\n',
        '    print(f"✅ ADK installed: v{adk_ver}")\n',
        'except Exception:\n',
        '    print(\'❌ ADK not found. Run: pip install "google-adk[extensions,eval]"\')\n',
    ]),

    # ── THEORY: API Key ──
    ("markdown", [
        "## 1.2 API Key Configuration\n",
        "\n",
        "### Where to Get a Key\n",
        "1. Go to https://aistudio.google.com/app/apikey\n",
        "2. Click \"Create API Key\"\n",
        "3. Copy the key (starts with `AIza...`)\n",
        "\n",
        "### How ADK Finds Your Key\n",
        "ADK's Gemini client looks for the key in this order:\n",
        "1. `GOOGLE_API_KEY` environment variable\n",
        "2. Application Default Credentials (for Vertex AI)\n",
        "\n",
        "**Best practice**: Store the key in a `.env` file (never commit to git!)\n",
        "and load it at runtime. This cell does exactly that.\n",
    ]),

    # ── LOAD ENV ──
    ("code", ENV_LOAD),

    # ── THEORY: Core imports explained ──
    ("markdown", [
        "## 1.3 Core ADK Imports — What Each Module Does\n",
        "\n",
        "| Import | Purpose |\n",
        "|---|---|\n",
        "| `google.adk.Agent` | The agent class — defines the LLM, instructions, and tools |\n",
        "| `google.adk.runners.Runner` | Executes the agent loop (send→LLM→respond→repeat) |\n",
        "| `google.adk.sessions.InMemorySessionService` | Stores conversation state in RAM (use DB-backed for production) |\n",
        "| `google.genai.types.Content, Part` | Message types — **NOT** from `google.adk.types` in v2.x! |\n",
        "| `asyncio` | Session creation is async in ADK 2.x; we need `await` |\n",
        "\n",
        "> **Important ADK 2.x change:** Content and Part live in `google.genai.types`,\n",
        "> not `google.adk.types`. This is because ADK v2.x unified its type system\n",
        "> with the Google GenAI SDK.\n",
    ]),

    ("code", IMPORTS_BASE),

    # ── THEORY: First Agent Walkthrough ──
    ("markdown", [
        "## 1.4 Your First Agent — A Line-by-Line Walkthrough\n",
        "\n",
        "### What We're Building\n",
        "A minimal agent that greets the user. This is the \"Hello World\" of ADK.\n",
        "\n",
        "### The 4 Steps to Run Any Agent\n",
        "1. **Define the Agent** — name, model, instruction (system prompt)\n",
        "2. **Create a Session** — a container for conversation state (async!)\n",
        "3. **Create a Runner** — the execution engine\n",
        "4. **Call `runner.run()`** — sends message, iterates over streaming events\n",
        "\n",
        "### Understanding Events\n",
        "`runner.run()` returns a **generator of Events**. Each Event represents\n",
        "one \"thing that happened\":\n",
        "- A text chunk from the LLM (streaming)\n",
        "- A tool call being made\n",
        "- A tool result being received\n",
        "- An error\n",
        "\n",
        "You iterate over events to stream the response in real time.\n",
    ]),

    ("code", [
        '# ═══════════════════════════════════════════════════════════════════\n',
        '# YOUR FIRST AGENT — Step-by-step with inline comments\n',
        '# ═══════════════════════════════════════════════════════════════════\n',
        '\n',
        '# ─── Step 1: Define the Agent ────────────────────────────────────\n',
        '# An Agent is the core building block. It wraps an LLM with a system\n',
        '# prompt (instruction) and optional tools.\n',
        'async def main():\n',
        '    agent = Agent(\n',
        '        name="greeter",               # Unique ID for this agent (used in logs/routing)\n',
        '        model="gemini-2.5-flash",     # Which LLM to use — fast and capable\n',
        '        instruction="You are a friendly greeter. Answer in ONE sentence. 😊",\n',
        '        # ↑ The instruction is the "system prompt" — it defines the agent\'s personality\n',
        '        #   and behavior. Be specific! Vague instructions = unpredictable behavior.\n',
        '    )\n',
        '\n',
        '    # ─── Step 2: Create a Session (ASYNC in ADK 2.x!) ──────────\n',
        '    # A session is like a "chat instance" — it stores the conversation\n',
        '    # history and state for one user\'s interaction.\n',
        '    # InMemorySessionService keeps everything in RAM (good for dev).\n',
        '    # For production, use a database-backed session service.\n',
        '    svc = InMemorySessionService()\n',
        '    session = await svc.create_session(\n',
        '        app_name="tutorial",    # Groups sessions under an app\n',
        '        user_id="user1",        # Identifies the user\n',
        '        session_id="s1"         # Unique session ID (like a chat thread ID)\n',
        '    )\n',
        '    print(f"Session created: {session.id}")  # Verify session exists\n',
        '\n',
        '    # ─── Step 3: Create the Runner ──────────────────────────────\n',
        '    # The Runner ties together: Agent + Session Service + Memory Service\n',
        '    # It orchestrates the agent loop (send→LLM→respond→repeat)\n',
        '    runner = Runner(\n',
        '        agent=agent,               # Which agent to run\n',
        '        app_name="tutorial",       # Must match session\'s app_name\n',
        '        session_service=svc,        # Where sessions are stored\n',
        '    )\n',
        '\n',
        '    # ─── Step 4: Build the Message ──────────────────────────────\n',
        '    # ADK uses Content and Part from google.genai.types\n',
        '    # Content = a message (like one line in a chat)\n',
        '    # Part = a piece of content inside a message (text, image, function call, etc.)\n',
        '    msg = Content(\n',
        '        role="user",  # Who sent this message? "user" or "model"\n',
        '        parts=[Part.from_text(text="Hello! Who are you?")]\n',
        '    )\n',
        '\n',
        '    # ─── Step 5: Run and Stream Events ──────────────────────────\n',
        '    # runner.run() returns a GENERATOR of events — iterate to stream\n',
        '    # Each event has: .author (who produced it), .content (what was produced)\n',
        '    print("User: Hello! Who are you?\\n")\n',
        '    for event in runner.run(\n',
        '        user_id="user1",            # Must match session\'s user_id\n',
        '        session_id=session.id,      # Which session to continue\n',
        '        new_message=msg             # The new user message\n',
        '    ):\n',
        '        # ─── Filter: only show model text responses ────────────\n',
        '        if event.content and event.content.parts:\n',
        '            for part in event.content.parts:\n',
        '                # part.text = plain text from the LLM\n',
        '                # part.thought = "thinking" content (skip these)\n',
        '                # part.function_call = LLM wants to call a tool\n',
        '                # part.function_response = tool result\n',
        '                if part.text and not part.thought:\n',
        '                    print(f"[{event.author}]: {part.text}")\n',
        '    print("\\n✅ First agent ran successfully!")\n',
        '\n',
        '# ─── Execute the async function ─────────────────────────────────\n',
        '# In Jupyter, use "await" (not asyncio.run) because Jupyter already\n',
        '# has a running event loop.\n',
        'await main()\n',
    ]),

    # ── THEORY: Understanding the Output ──
    ("markdown", [
        "### What Just Happened? (The Agent Loop, Step by Step)\n",
        "\n",
        "1. **Runner received** the user message `\"Hello! Who are you?\"`\n",
        "2. **Runner sent to LLM**: The message + agent instruction + conversation history\n",
        "3. **LLM generated**: A text response (no tool calls needed — simple greeting)\n",
        "4. **Runner yielded the Event** containing the text\n",
        "5. **Our loop printed it**\n",
        "\n",
        "The agent had no tools, so the LLM could only produce text. In later\n",
        "notebooks, we'll add tools so the agent can search the web, run code,\n",
        "and call APIs.\n",
        "\n",
        "### Why Async Sessions?\n",
        "\n",
        "ADK 2.x made session creation async because production session services\n",
        "(Cloud Firestore, Spanner) require async I/O. The in-memory service is\n",
        "also async for API consistency — you write the same code in dev and prod.\n",
    ]),

    # ── CLI reference ──
    ("markdown", [
        "## 1.5 The `adk` CLI (Reference)\n",
        "\n",
        "ADK ships with a CLI for project management. You don't need it for\n",
        "programmatic usage (which is what these notebooks teach), but it's\n",
        "useful for scaffolding and deployment:\n",
        "\n",
        "| Command | What it does |\n",
        "|---|---|\n",
        "| `adk create my_agent` | Scaffolds a new agent project with agent.py, .env, __init__.py |\n",
        "| `adk run my_agent` | Runs agent in interactive terminal mode |\n",
        "| `adk web my_agent` | Launches a browser-based chat UI at http://localhost:8000 |\n",
        "| `adk deploy cloud_run` | Deploys to Google Cloud Run (one command!) |\n",
        "| `adk deploy agent_engine` | Deploys to Vertex AI Agent Engine (enterprise) |\n",
        "\n",
        "## Summary\n",
        "\n",
        "| Concept | Key point |\n",
        "|---|---|\n",
        "| **Agent** | LLM + instruction + tools. The building block. |\n",
        "| **Runner** | Executes the agent loop (send→LLM→respond→repeat) |\n",
        "| **Session** | Stores conversation state for one chat (async creation) |\n",
        "| **Event** | One thing that happened (text, tool call, error) |\n",
        "| **Content/Part** | Message format — from `google.genai.types`, NOT `google.adk.types` |\n",
        "\n",
        "**Next:** [02_first_agent.ipynb](./02_first_agent.ipynb) — deep dive into Agent, Runner, Sessions.\n",
    ]),
])

print("✅ 01_installation_setup.ipynb rewritten with deep theory")

# ═══════════════════════════════════════════════════════════════════
# NOTEBOOK 02
# ═══════════════════════════════════════════════════════════════════

save('02_first_agent.ipynb', [
    ("markdown", [
        "# 02 — The Agent Class: Deep Dive\n",
        "\n",
        "## What You'll Learn\n",
        "- Every field on the `Agent` class and what it controls\n",
        "- How Runner manages the agent lifecycle\n",
        "- Sessions, multi-turn conversations, and state persistence\n",
        "- Models, instructions (system prompts), and `output_key`\n",
        "\n",
        "> **Prerequisites:** Notebook 01 (installation & first agent)\n",
    ]),

    ("markdown", [
        "## 2.1 The Agent Class — Complete Reference\n",
        "\n",
        "`Agent` is the central abstraction in ADK. Every agent is defined by:\n",
        "\n",
        "```python\n",
        "Agent(\n",
        "    name='...',              # Required: unique identifier\n",
        "    model='...',             # Required: which LLM to use\n",
        "    instruction='...',       # The system prompt (behavior definition)\n",
        "    description='...',       # For multi-agent discovery\n",
        "    tools=[...],             # Tools the agent can use\n",
        "    sub_agents=[...],        # Child agents this agent can delegate to\n",
        "    output_key='...',        # Auto-save response to session.state\n",
        "    # + callbacks, code_executor, planner, etc. (covered later)\n",
        ")\n",
        "```\n",
        "\n",
        "### The `name` Field\n",
        "- Must be unique within an agent hierarchy\n",
        "- Used in event.author to identify who produced what\n",
        "- Used in multi-agent routing (`transfer_to_agent`)\n",
        "\n",
        "### The `model` Field\n",
        "- String like `'gemini-2.5-flash'` or a `BaseLlm` instance\n",
        "- LiteLLM format supported: `'openrouter:provider/model'`\n",
        "- The model MUST support function calling (all Gemini 2 models do)\n",
        "\n",
        "### The `instruction` Field\n",
        "- This is the **system prompt** — it defines the agent's entire behavior\n",
        "- Can be a string OR a callable (dynamic instructions)\n",
        "- **Best practice:** Include ROLE, TOOLS, CONSTRAINTS, OUTPUT sections\n",
    ]),

    ("code", IMPORTS_BASE + ENV_LOAD),

    ("markdown", [
        "## 2.2 Instructions — The Art of Prompting Agents\n",
        "\n",
        "The instruction is the most important field. A well-written instruction\n",
        "is the difference between a useful agent and a frustrating one.\n",
        "\n",
        "### Good vs Bad Instructions\n",
        "\n",
        "```python\n",
        '# BAD: Vague, no constraints\n',
        'instruction = "Be helpful"\n',
        "\n",
        "# GOOD: Role, tools, constraints, output format\n",
        'instruction = """\n',
        'ROLE: You are a precise research assistant.\n',
        'TOOLS: Use google_search for current data. Always cite sources.\n',
        'CONSTRAINTS: Never fabricate facts. Keep answers under 3 paragraphs.\n',
        'OUTPUT: End with "Sources:" and list URLs.\n',
        '"""\n',
        "```\n",
        "\n",
        "### Instruction Sections to Include\n",
        "1. **ROLE**: Who the agent is (\"You are a...\")\n",
        "2. **TOOLS**: When and how to use each tool\n",
        "3. **CONSTRAINTS**: Hard rules (\"never do X\", \"always do Y\")\n",
        "4. **OUTPUT**: Expected format (\"Return as bullet points\", \"Use markdown\")\n",
    ]),

    ("code", [
        '# ═══════════════════════════════════════════════════════════════════\n',
        '# CREATING AGENTS WITH GOOD INSTRUCTIONS\n',
        '# ═══════════════════════════════════════════════════════════════════\n',
        '\n',
        '# Example 1: A simple agent with a minimal instruction\n',
        'simple_agent = Agent(\n',
        '    name="simple_bot",\n',
        '    model="gemini-2.5-flash",\n',
        '    instruction="You are a helpful assistant. Be concise.",\n',
        ')\n',
        'print(f"Created: {simple_agent.name} | model={simple_agent.model}")\n',
        '\n',
        '# Example 2: A production-quality instruction\n',
        '# This pattern is what you should use for real agents\n',
        'PRODUCTION_INSTRUCTION = """\n',
        'ROLE: You are a technical documentation assistant for a software company.\n',
        'TOOLS: None currently — answer from your training knowledge.\n',
        'CONSTRAINTS:\n',
        '  - Never make up API endpoints or code that doesn\'t exist\n',
        '  - If unsure, say "I don\'t know" and suggest where to look\n',
        '  - Keep answers under 4 paragraphs\n',
        'OUTPUT: Use markdown formatting. Code in ``` blocks with language tags.\n',
        '"""\n',
        '\n',
        'pro_agent = Agent(\n',
        '    name="docs_assistant",\n',
        '    model="gemini-2.5-flash",\n',
        '    instruction=PRODUCTION_INSTRUCTION,\n',
        '    description="Helps with technical documentation questions",\n',
        ')\n',
        'print(f"Created: {pro_agent.name} with detailed instruction")\n',
    ]),

    ("markdown", [
        "## 2.3 Runner & Sessions — How Execution Works\n",
        "\n",
        "### The Runner Class\n",
        "`Runner` is the execution engine. It:\n",
        "1. Takes an `Agent` and a `SessionService`\n",
        "2. Manages the agent loop (send to LLM → get response → execute tools → repeat)\n",
        "3. Yields `Event` objects for streaming\n",
        "4. Handles errors and retries\n",
        "\n",
        "### Sessions: The Agent's Memory\n",
        "A **session** is a container that holds:\n",
        "- **Conversation history** (all messages exchanged)\n",
        "- **State** (a dict for storing data across turns)\n",
        "- **Artifacts** (files created during the conversation)\n",
        "\n",
        "Sessions are identified by `(app_name, user_id, session_id)`.\n",
        "This triplet uniquely identifies one conversation.\n",
        "\n",
        "### Session Lifecycle\n",
        "```\n",
        "create_session() → [turn 1] → [turn 2] → ... → session persists\n",
        "```\n",
        "Each call to `runner.run()` with the same session_id continues\n",
        "the conversation — the LLM sees all previous messages.\n",
    ]),

    ("code", [
        '# ═══════════════════════════════════════════════════════════════════\n',
        '# RUNNER AND SESSION DEMO — Single turn with event inspection\n',
        '# ═══════════════════════════════════════════════════════════════════\n',
        '\n',
        'async def demo_runner():\n',
        '    # ─── Create an agent ─────────────────────────────────────────\n',
        '    agent = Agent(\n',
        '        name="inspector",\n',
        '        model="gemini-2.5-flash",\n',
        '        instruction="You are a helpful bot. Answer questions clearly.",\n',
        '    )\n',
        '\n',
        '    # ─── Create session (ASYNC — must await) ─────────────────────\n',
        '    svc = InMemorySessionService()\n',
        '    session = await svc.create_session(\n',
        '        app_name="tutorial", user_id="user1", session_id="runner_demo"\n',
        '    )\n',
        '\n',
        '    # ─── Create runner ───────────────────────────────────────────\n',
        '    runner = Runner(agent=agent, app_name="tutorial", session_service=svc)\n',
        '\n',
        '    # ─── Build message ───────────────────────────────────────────\n',
        '    msg = Content(role="user", parts=[Part.from_text(text="What is your name?")])\n',
        '\n',
        '    # ─── Run and inspect every event ─────────────────────────────\n',
        '    print("Streaming events from runner.run():\\n")\n',
        '    for event in runner.run(user_id="user1", session_id=session.id, new_message=msg):\n',
        '        # Each event tells us WHO produced it and WHAT was produced\n',
        '        if event.content and event.content.parts and event.author != "user":\n',
        '            for part in event.content.parts:\n',
        '                if part.text:\n',
        '                    # part.text = the actual text content\n',
        '                    print(f"  [{event.author}] TEXT: {part.text[:200]}")\n',
        '                if part.function_call:\n',
        '                    # part.function_call = LLM wants to invoke a tool\n',
        '                    print(f"  [{event.author}] TOOL CALL: {part.function_call.name}")\n',
        '                if part.function_response:\n',
        '                    # part.function_response = result from tool execution\n',
        '                    print(f"  [{event.author}] TOOL RESULT: {part.function_response.name}")\n',
        '\n',
        'await demo_runner()\n',
    ]),

    ("markdown", [
        "## 2.4 Multi-Turn Conversations\n",
        "\n",
        "One of ADK's key features: **conversations persist across turns**.\n",
        "When you call `runner.run()` again with the same `session_id`,\n",
        "the agent sees all previous messages in that session.\n",
        "\n",
        "This is fundamentally different from raw LLM APIs where you must\n",
        "manually track and resend the entire conversation history.\n",
    ]),

    ("code", [
        '# ═══════════════════════════════════════════════════════════════════\n',
        '# MULTI-TURN CONVERSATION — Agent remembers across calls\n',
        '# ═══════════════════════════════════════════════════════════════════\n',
        '\n',
        'async def multi_turn():\n',
        '    # ─── Create a single agent + session ─────────────────────────\n',
        '    agent = Agent(\n',
        '        name="memory_bot",\n',
        '        model="gemini-2.5-flash",\n',
        '        instruction="You are a helpful assistant. Remember user facts.",\n',
        '    )\n',
        '    svc = InMemorySessionService()\n',
        '    s = await svc.create_session(app_name="t", user_id="u", session_id="mt")\n',
        '    r = Runner(agent=agent, app_name="t", session_service=svc)\n',
        '\n',
        '    # ─── Turn 1: Tell the agent something ────────────────────────\n',
        '    m1 = Content(role="user", parts=[Part.from_text(\n',
        '        text="My name is Alice and I live in Berlin."\n',
        '    )])\n',
        '    print("Turn 1 — User: My name is Alice and I live in Berlin.\\n")\n',
        '    for e in r.run(user_id="u", session_id=s.id, new_message=m1):\n',
        '        if e.content and e.content.parts:\n',
        '            for p in e.content.parts:\n',
        '                if p.text and not p.thought:\n',
        '                    print(f"  Agent: {p.text}")\n',
        '\n',
        '    # ─── Turn 2: Ask about the remembered fact ───────────────────\n',
        '    # SAME session_id → agent sees Turn 1\'s messages!\n',
        '    m2 = Content(role="user", parts=[Part.from_text(\n',
        '        text="What\'s my name and where do I live?"\n',
        '    )])\n',
        '    print("\\nTurn 2 — User: What\'s my name and where do I live?\\n")\n',
        '    for e in r.run(user_id="u", session_id=s.id, new_message=m2):\n',
        '        if e.content and e.content.parts:\n',
        '            for p in e.content.parts:\n',
        '                if p.text and not p.thought:\n',
        '                    print(f"  Agent: {p.text}")\n',
        '\n',
        'await multi_turn()\n',
    ]),

    ("markdown", [
        "## 2.5 `output_key` — Saving Agent Responses to State\n",
        "\n",
        "`output_key` tells ADK: \"Save this agent's final text response into\n",
        "`session.state[key]`.\" This is the primary way to pass data between\n",
        "agents in a pipeline.\n",
        "\n",
        "### How It Works\n",
        "1. Agent runs and produces a text response\n",
        "2. ADK automatically saves that text to `session.state[output_key]`\n",
        "3. Downstream agents or code can read `session.state[output_key]`\n",
        "\n",
        "### Use Cases\n",
        "- **Pipeline data passing**: Agent A extracts → Agent B transforms\n",
        "- **Caching**: Avoid re-running expensive operations\n",
        "- **Inspection**: See what each agent produced\n",
    ]),

    ("code", [
        '# ═══════════════════════════════════════════════════════════════════\n',
        '# OUTPUT_KEY DEMO — Auto-saving agent responses to session.state\n',
        '# ═══════════════════════════════════════════════════════════════════\n',
        '\n',
        'async def output_key_demo():\n',
        '    # Agent configured to save its response under "keywords"\n',
        '    extractor = Agent(\n',
        '        name="extractor",\n',
        '        model="gemini-2.5-flash",\n',
        '        instruction="Extract exactly 3 keywords from the text. Return comma-separated ONLY.",\n',
        '        output_key="keywords",  # ← THIS is the magic: auto-saves to session.state["keywords"]\n',
        '    )\n',
        '\n',
        '    svc = InMemorySessionService()\n',
        '    s = await svc.create_session(app_name="t", user_id="u", session_id="ok")\n',
        '    r = Runner(agent=extractor, app_name="t", session_service=svc)\n',
        '\n',
        '    # Send text for extraction\n',
        '    m = Content(role="user", parts=[Part.from_text(\n',
        '        text="Machine learning models can hallucinate when lacking diverse training data."\n',
        '    )])\n',
        '\n',
        '    # Run the agent (we don\'t care about streaming here)\n',
        '    for _ in r.run(user_id="u", session_id=s.id, new_message=m):\n',
        '        pass  # Consume all events to complete execution\n',
        '\n',
        '    # ─── Read the saved output from session state ────────────────\n',
        '    # get_session() is ALSO async in ADK 2.x!\n',
        '    sess = await svc.get_session(app_name="t", user_id="u", session_id="ok")\n',
        '    print("Session state keys:", list(sess.state.keys()))\n',
        '    print("Keywords extracted:", sess.state.get("keywords", "NOT SET"))\n',
        '    \n',
        '    # session.state is a regular Python dict — you can read/write freely\n',
        '    # This is how pipelines pass data between stages!\n',
        '\n',
        'await output_key_demo()\n',
    ]),

    ("markdown", [
        "## Summary\n",
        "\n",
        "| Concept | What it does |\n",
        "|---|---|\n",
        "| `Agent.name` | Unique ID for routing and event tracking |\n",
        "| `Agent.model` | LLM to use (Gemini, OpenAI, Anthropic, Ollama...) |\n",
        "| `Agent.instruction` | System prompt — defines behavior, constraints, output |\n",
        "| `Agent.output_key` | Auto-saves response to session.state |\n",
        "| `Runner` | Executes agent loop, yields Events |\n",
        "| `Session` | Stores conversation history + state (async create/get) |\n",
        "| `Event` | One step in the agent loop (text, tool call, error) |\n",
        "\n",
        "**Next:** [03_tools.ipynb](./03_tools.ipynb) — adding capabilities with tools.\n",
    ]),
])

print("✅ 02_first_agent.ipynb rewritten with deep theory")

print("\nAll notebooks being regenerated with theory + inline comments...")
print("(01, 02 done; 03-08 to follow in next write)")
